Repository debopriyadey/DSA, pull requests merged in 2022-10, with the labels that each got.

#3 Create LinearSearch.cpp
  Algorithm/LinearSearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 BinarySearch Algorithm added
  Algorithm/BinarySearch.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 binarysearch.cpp
  binarysearch.cpp
Labels: hacktoberfest-accepted

#6 Create MergeSort.cpp
  Algorithm/MergeSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#9 Create ThreeSum.cpp
  Basic Programs/ThreeSum.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#10 Create MergeTwoSortedArrays.cpp
  Basic Programs/MergeTwoSortedArrays.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 Create quickselect.java
  Basic Programs/quickselect.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 Quick Sort Algo Added
  Algorithm/QuickSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#13 Heap Sort Added
  Algorithm/HeapSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 Create bfs_transversal
  Algorithm/bfs_transversal
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 Create dfs_transversal.cpp
  Algorithm/C++/dfs_transversal.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 Create heightofanode.cpp
  Algorithm/heightofanode.cpp
Labels: hacktoberfest-accepted

#18 Create level_order_traversal.cpp
  Algorithm/level_order_traversal.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#17 Create bricksort.cpp
  Algorithm/C++/bricksort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 Create spiral_level_order_traversal.cpp
  Algorithm/spiral_level_order_traversal.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#21 Create CoinChange.cpp
  Algorithm/C++/CoinChange.cpp
  Algorithm/C++/CoinChange.exe
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#22 Create DijkstraShortestPath.cpp
  Algorithm/C++/DijkstraShortestPath.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#23 Added Russian Peasant (Multiply two numbers using bitwise operators)
  Algorithm/C++/RussianPeasant.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#24 Create Updated Algo
  Updated Algo
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 Create Kadane's Updated Algo
  Kadane's Updated Algo
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Added Booth'sAlgorithm.cpp
  Algorithm/C++/Booth'sAlgorithm.cpp
  Algorithm/C++/PandigitalConcatenations.cpp
  Basic Programs/Pascal'sTriangle.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#27 Create 1_TwoSum.cpp
  LeetCode_Top100/1_TwoSum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#28 Create 2_AddTwoNumbers.cpp
  LeetCode_Top100/2_AddTwoNumbers.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#30 Create 4_MedianofTwoSortedArrays.cpp
  LeetCode_Top100/4_MedianofTwoSortedArrays.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#34 Create 21_MergeTwoSortedLists.cpp
  LeetCode_Top100/21_MergeTwoSortedLists.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#33 Create 22_GenerateParentheses.py
  LeetCode_Top100/22_GenerateParentheses
Labels: hacktoberfest, hacktoberfest-accepted

#32 Create 20_ValidParentheses.cpp
  LeetCode_Top100/20_ValidParentheses
Labels: hacktoberfest, hacktoberfest-accepted

#31 Create 5_LongestPalindromicString.py
  LeetCode_Top100/5_LongestPalindromicString.py
Labels: hacktoberfest, hacktoberfest-accepted
